
<div id="baner">

    <div class="container">
        <div class="image-slider-wrapper">
            <ul id="image_slider">
                <li><img src="<?php echo $this->getSkinUrl('images/slide-1.jpg'); ?>"></li>
                <li><img src="<?php echo $this->getSkinUrl('images/slide-2.jpg'); ?>"></li>
                <li><img src="<?php echo $this->getSkinUrl('images/slide-3.jpg'); ?>"></li>
                <li><img src="<?php echo $this->getSkinUrl('images/slide-4.jpg'); ?>"></li>
            </ul>			
            <div class="pager">
            </div>
        </div>
    </div>

</div><div id="box-3-offer">
    <div class="box-3-offer-column"><img src="<?php echo $this->getSkinUrl('images/box3-1.jpg'); ?>" alt="" /></div>
    <div class="box-3-offer-column"><img src="<?php echo $this->getSkinUrl('images/box3-2.jpg'); ?>" alt="" /></div>
    <div class="box-3-offer-column box-3-offer-last"><img src="<?php echo $this->getSkinUrl('images/box3-3.jpg'); ?>" alt="" /></div>

    <div class="clr"></div>
</div>
