<div id="box-slide-offer">

    <h2 class="box-title">Our Bestsellers</h2>

    <div class="previous-btn">
        <button name="previous" id="previous" type="button"><img alt="" src="<?php echo $this->getSkinUrl('images/prev-btn.jpg'); ?>" /></button> 			
    </div>	

    <div class="next-btn">
        <button name="next" id="next" type="button"><img alt="" src="<?php echo $this->getSkinUrl('images/next-btn.jpg'); ?>" /></button> 				
    </div>

    <div id="carouseldiv">

        <div class="set box-slide-product">
            <img alt="" src="<?php echo $this->getSkinUrl('images/products/bed1.jpg'); ?>" />		
            <h3 class="slider-product-title">Navy Blue Gingham Duvet</h3>
            <p class="box-slide-description">Hypoallergenic &amp; Cotton Cover Medium-weight Hollowfibre</p>
            <p class="box-slide-price box-slide-price-discound">From &pound;65.00</p>
            <p class="box-slide-special-price">Special Price: &pound;45.00</p>
        </div>


        <div class="set box-slide-product"> 
            <img alt="" src="<?php echo $this->getSkinUrl('images/products/bed2.jpg'); ?>" />	
            <h3 class="slider-product-title">Blue Stripe Duvet Set &amp; Pillows</h3>
            <p class="box-slide-description">Hypoallergenic &amp; Cotton Cover Medium-weight Hollowfibre</p>
            <p class="box-slide-price">From &pound;65.00</p>
        </div>


        <div class="set box-slide-product">
            <img alt="" src="<?php echo $this->getSkinUrl('images/products/bed1.jpg'); ?>" />		
            <h3 class="slider-product-title">Blue Stripe Duvet Set &amp; Pillows</h3>
            <p class="box-slide-description">Hypoallergenic &amp; Cotton Cover Medium-weight Hollowfibre</p>
            <p class="box-slide-price">From &pound;65.00</p>
        </div>

        <div class="set box-slide-product">
            <img alt="" src="<?php echo $this->getSkinUrl('images/products/bed3.jpg'); ?>" />	
            <h3 class="slider-product-title">Navy Blue Gingham Duvet</h3>
            <p class="box-slide-description">Hypoallergenic &amp; Cotton Cover Medium-weight Hollowfibre</p>
            <p class="box-slide-price">From &pound;65.00</p>
        </div>

        <div class="set box-slide-product">
            <img alt="" src="<?php echo $this->getSkinUrl('images/products/bed1.jpg'); ?>" />	
            <h3 class="slider-product-title">Navy Blue Gingham Duvet</h3>
            <p class="box-slide-description">Hypoallergenic &amp; Cotton Cover Medium-weight Hollowfibre</p>
            <p class="box-slide-price box-slide-price-discound">From &pound;65.00</p>
            <p class="box-slide-special-price">Special Price: &pound;45.00</p>
        </div>

        <div class="set box-slide-product">
            <img alt="" src="<?php echo $this->getSkinUrl('images/products/bed1.jpg'); ?>" />	
            <h3 class="slider-product-title">Navy Blue Gingham Duvet</h3>
            <p class="box-slide-description">Hypoallergenic &amp; Cotton Cover Medium-weight Hollowfibre</p>
            <p class="box-slide-price box-slide-price-discound">From &pound;65.00</p>
            <p class="box-slide-special-price">Special Price: &pound;45.00</p>
        </div>


        <div class="set box-slide-product"> 
            <img alt="" src="<?php echo $this->getSkinUrl('images/products/bed2.jpg'); ?>" />	
            <h3 class="slider-product-title">Blue Stripe Duvet Set &amp; Pillows</h3>
            <p class="box-slide-description">Hypoallergenic &amp; Cotton Cover Medium-weight Hollowfibre</p>
            <p class="box-slide-price">From &pound;65.00</p>
        </div>


        <div class="set box-slide-product">
            <img alt="" src="<?php echo $this->getSkinUrl('images/products/bed1.jpg'); ?>" />		
            <h3 class="slider-product-title">Blue Stripe Duvet Set &amp; Pillows</h3>
            <p class="box-slide-description">Hypoallergenic &amp; Cotton Cover Medium-weight Hollowfibre</p>
            <p class="box-slide-price">From &pound;65.00</p>
        </div>
    </div>
</div>

