<div id="bottom-links">
	
		<div id="bottom-left">
		
			<div class="bottom-column-left column-one">
			
				<h4>Contact Us</h4>
				<p>Email: <a href="mailto:info@purelivingcolletion.com">info@purelivingcolletion.com</a></p>
				<p>Tel: 01234 56789</p>
				<p>Mon - Fr 9.00 - 5.30 GMT</p>
				
			</div><!--bottom-column-left-->
			<div class="bottom-column-right column-two">
			
				<h4>Customer Service</h4>
				<ul>
				<li><a href="#">Ordering Information</a></li>
				<li><a href="#">Our No Quibble Guarante</a></li>
				<li><a href="#">Delivery Information</a></li>
				<li><a href="#">Cancellations, Returns &amp; Exchange</a></li>
				</ul>
			
			</div><!--bottom-column-right-->
			
										<div class="clr"></div>
										
			<div id="payment"><img alt="" src="<?php echo $this->getSkinUrl('images/payment.jpg'); ?>" /></div><!--payment-->							
		
		</div><!--bottom left-->
		
		<div id="bottom-right">
		
			<div class="bottom-column-left column-three">
			
				<h4>Help Guides</h4>
				<ul>
				<li><a href="#">Which Duvet?</a></li>
				<li><a href="#">Which Pillow?</a></li>
				<li><a href="#">Which Mattress Toppper?</a></li>
				<li><a href="#">Which Mattress Protector?</a></li>
				<li><a href="#">Duvet Reviews</a></li>
				<li><a href="#">Pillow Reviews</a></li>
				<li><a href="#">Mattress Toppper Reviews</a></li>
				<li><a href="#">Mattress Protector Reviews</a></li>
				<li><a href="#">Bedding Glossary</a></li>
				</ul>
				
			</div><!--bottom-column-left-->
			
			<div class="bottom-column-right column-four">
			
				<h4>About Our Site</h4>
				<ul>
				<li><a href="#">Sitemap</a></li>
				<li><a href="#">Privacy and Data Protection</a></li>
				<li><a href="#">Security</a></li>
				<li><a href="#">Payment Methods</a></li>
				<li><a href="#">VAT and Duties</a></li>
				<li><a href="#">Terms and Conditions</a></li>
				</ul>
			
			</div><!--bottom-column-right-->
			
										<div class="clr"></div>
		
		</div><!--bottom right-->
	
										<div class="clr"></div>
	
	</div><!--bottom links-->

