<div class="nav-container">

    <ul id="nav">

        <li><a href="#">Bed Linen</a></li>
        <li><a href="#">Blankets, &amp; Throws Bedspreads</a></li>
        <li><a href="#">Cushions</a></li>
        <li><a href="#">Duvets</a></li>
        <li><a href="#">Pillows</a></li>
        <li><a href="#">Mattress Toppers &amp; Protectors</a></li>
        <li><a href="#">Children&rsquo;s Bedding</a></li>
        <li><a id="active" href="#">Offers</a></li>
        <li><a href="#">Style</a></li>

    </ul><!--nav-->

    <div class="clr"></div>


</div><!--nav-container-->