<div id="newsletter-delivery">
	
		<div id="newsletter">
			<h3>Sign up for news and exclusive offers!</h3>
			
			<form id="newsletter-input" action="#" method="get">		
					<div class="form-newsletter"> 
						<input type="text" name="" value="" class="input-text" /> 
						<button type="submit" title="Search" class="button">Sign Up</button>
					</div><!--newsletter-input--> 
			</form> 
			
		</div><!--newsletter-->
		
		<div id="delivery">
			<h3>Free delivery for orders over &pound;75</h3>
			<p>UK Courier Delivery: &pound;4.95 within 5 working days or &pound;7.95 for 2-3 day</p>
			<p>Wordwide Delivery: Priced at checkout</p>
		</div><!--delivery-->
	
										<div class="clr"></div>
	
	</div><!--newsletter delivery-->