



<div id="footer">
    <?php
//    $blocks = Mage::app()->getLayout()->getAllBlocks();
//    var_dump($blocks);
    ?>
    <p>Copyright 2011 Pure Living Collection. All Rights Reserved. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum facilisis felis lorem. Sed pellentesque dapibus consequat.</p>
    <p>Curabitur nisi nisi, aliquam eu vehicula porttitor, vulputate ut tellus. Nulla massa quam, lacinia a adipiscing ac, fermentum volutpat velit. Nulla ac tortor eget justo accumsan facilisis. In hac habitasse platea dictumst. Nulla vehicula tortor vel nisi convallis a blandit turpis bibendum. Sed id diam no tasse platea dictumst. Nutasse platea dictumst. Nulla lla n.</p>
    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum facilisis felis lorem. Sed pellentesque dapibus consequat.</p>

</div>
