

<div class="header-container">
    <div class="header">

        <h1 class="logo"><a href="#"><img src="<?php echo $this->getSkinUrl('images/logo.jpg'); ?>" alt="" /></a></h1> 	

        <div class="quick-access"> 
 
            <ul class="links"> 
                <li><a href="#">Sign In</a></li> 
                <li><a href="#">My Account</a></li> 
                <li><a href="#">My Wishlist (21 items)</a></li> 
                <li class="last"><a href="#">My Shopping Bag (5 items)</a></li> 
            </ul> <!--links-->

            <div class="clr"></div>

            <form id="search_mini_form" action="#" method="get">		
                <div class="form-search"> 
                    <input id="search" type="text" name="q" value="" class="input-text" /> 
                    <button type="submit" title="Search" class="button"></button> 
                </div><!--form-search--> 
            </form> 		

            <div id="checkout-button"><a href="#">Checkout</a></div><!--checkout-button-->

            <div class="clr"></div>

        </div><!--quick-access-->	

        <div class="clr"></div>

    </div><!--header-->
</div>        